springdoc:
  swagger-ui:
    path: /documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /api-docs

openapi:
  dev-url: http://localhost:8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:./products
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    es.com.between: debug